<?php
// $Id$

/**
 *  @file
 *  Media YouTube provides a stream wrapper and formatters for videos provided
 *  by YouTube, available at http://youtube.com/.
 *
 *  @TODO:
 *  Hook into Media, allowing editors to enter a URL in a text box.
 *  Parse YouTube URL's.
 *  Create a video size transformer hook for media styles.
 *  Create a thumbnail importer for media styles/ image styles.
 *  Tie in YouTube API.
 *  Allow editors to search for videos to display on the browser.
 *  Allow editors to put in a youtube username to display on the browser.
 *  Allow editors to log in w/ their credentials.
 */

/**
 *  Create stream wrapper for YouTube videos.
 */
function media_youtube_stream_wrappers() {
  stream_wrapper_register('youtube', 'MediaYouTubeStreamWrapper');
  return array(
    'youtube' => array(
      'name' => t('YouTube videos'),
      'class' => 'MediaYouTubeStreamWrapper',
      'description' => t('Videos provided by YouTube.'),
    ),
  );
}

function media_youtube_theme($existing, $type, $theme, $path) {
  return array(
    'media_youtube_preview_style_old' => array(
      'variables' => array('style' => NULL),
    ),
    'media_youtube_preview_style' => array(
      'variables' => array('field_type' => NULL, 'container_name' => NULL, 'style_name' => NULL),
    ),
  );
}

function media_youtube_styles_containers() {
  return array(
    'media' => array(
      'media_youtube' => array(
        'label' => t('YouTube Styles'),
        'data' => array(
          'streams' => array(
            'youtube://',
          ),
          'mimetypes' => array(
            'application/octet-stream',
          ),
        ),
        'preview theme' => 'media_youtube_preview_style',
        'help' => t('YouTube Styles will display embedded YouTube videos and thumbnails to your choosing, such as by resizing, setting colors, and autoplay. You can !manage.', array('!manage' => l(t('manage your YouTube styles here'), 'admin/config/media/media-youtube-styles'))),
      ),
    ),
  );
}

function media_youtube_styles_styles() {
  return array(
    'media' => array(
      'media_youtube' => array(
        'youtube_preview' => array(
          'name' => 'youtube_preview',
          'effects' => array(
            array('label' => t('Autoplay'), 'name' => 'autoplay', 'data' => array('autoplay' => 1)),
            array('label' => t('Resize'), 'name' => 'resize', 'data' => array('width' => 320, 'height' => 240)),
          ),
        ),
        'youtube_full' => array(
          'name' => 'youtube_full',
          'effects' => array(
            array('label' => t('Autoplay'), 'name' => 'autoplay', 'data' => array('autoplay' => 0)),
            array('label' => t('Resize'), 'name' => 'resize', 'data' => array('width' => 640, 'height' => 480)),
          ),
        ),
      ),
    ),
  );
}

function media_youtube_styles_presets() {
  return array(
    'media' => array(
      'media_youtube' => array(
        'youtube_preview',
        'youtube_full',
      ),
    ),
  );
}

function theme_media_youtube_preview_style($variables) {
  $style_name = $variables['style_name'];
  $styles = styles_containers_available_styles('media', 'media_youtube');
  if (isset($styles[$style_name])) {
    $style = $styles[$style_name];
    $sample_video = variable_get('media_youtube_preview_sample_video_uri', 'youtube://v/-jubiv7QUco');
    $fullscreen_value = 'false';
    $autoplay = 'false';
    foreach ($style['effects'] as $effect) {
      switch ($effect['name']) {
        case 'autoplay':
          $autoplay = $effect['data']['autoplay'] ? 'true' : 'false';
          break;
        case 'resize':
          $width = $effect['data']['width'];
          $height = $effect['data']['height'];
          break;
        case 'fullscreen':
          $fullscreen_value = 'true';
          break;
      }
    }
    $url = 'http://www.youtube.com/v/-jubiv7QUco';
    $id = 'media-youtube-preview';
    $div_id = 'media-youtube-preview-wrapper';
    $flashvars = check_plain(drupal_http_build_query(array('playerMode' => 'embedded')));
    // <object width="425" height="344"><param name="movie" value="http://www.youtube.com/v/lZ-s3DRZJKY&hl=en&fs=1&"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/lZ-s3DRZJKY&hl=en&fs=1&" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="425" height="344"></embed></object>
    $output = <<<OUTPUT
          <div id="$div_id"><object type="application/x-shockwave-flash" height="$height" width="$width" data="$url" id="$id">
            <param name="movie" value="$url" />
            <param name="allowScriptAcess" value="sameDomain"/>
            <param name="quality" value="best"/>
            <param name="allowFullScreen" value="$fullscreen_value"/>
            <param name="bgcolor" value="#FFFFFF"/>
            <param name="scale" value="noScale"/>
            <param name="salign" value="TL"/>
            <param name="FlashVars" value="$flashvars" />
            <param name="wmode" value="transparent" />
          </object></div>
OUTPUT;
    return $output;
  }
}

/** @TODO: Remove below, it's CRUFT **/

/**
 * Implement hook_media_effect_info().
 */
function media_youtube_media_effect_info() {
  return array(
    'media_youtube_media_effect_info' => array(
      'label' => t('YouTube styles'),
      'streams' => array('youtube://'),
      'mimetypes' => array('application/octet-stream'),
      'preview-theme' => 'media_youtube_preview_style',
      'styles' => array(
        'thumbnail' => array(
          'name' => 'thumbnail',
          'module' => 'media_youtube',
          'effects' => array(
            array('label' => t('Autoplay'), 'name' => 'autoplay', 'data' => array('autoplay' => 1)),
            array('label' => t('Resize'), 'name' => 'resize', 'data' => array('width' => 320, 'height' => 240)),
          ),
        ),
        'youtube_full' => array(
          'name' => 'youtube_full',
          'module' => 'media_youtube',
          'effects' => array(
            array('label' => t('Autoplay'), 'name' => 'autoplay', 'data' => array('autoplay' => 0)),
            array('label' => t('Resize'), 'name' => 'resize', 'data' => array('width' => 640, 'height' => 480)),
          ),
        ),
      ),
    ),
  );
}

function theme_media_youtube_preview_style_old($variables) {
  $style = $variables['style'];
  $sample_video = variable_get('media_youtube_preview_sample_video_uri', 'youtube://v/-jubiv7QUco');
  $fullscreen_value = 'false';
  $autoplay = 'false';
  foreach ($style['effects'] as $effect) {
    switch ($effect['name']) {
      case 'autoplay':
        $autoplay = $effect['data']['autoplay'] ? 'true' : 'false';
        break;
      case 'resize':
        $width = $effect['data']['width'];
        $height = $effect['data']['height'];
        break;
      case 'fullscreen':
        $fullscreen_value = 'true';
        break;
    }
  }
  $url = 'http://www.youtube.com/v/-jubiv7QUco';
  $id = 'media-youtube-preview';
  $div_id = 'media-youtube-preview-wrapper';
  $flashvars = check_plain(drupal_http_build_query(array('playerMode' => 'embedded')));
  // <object width="425" height="344"><param name="movie" value="http://www.youtube.com/v/lZ-s3DRZJKY&hl=en&fs=1&"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/lZ-s3DRZJKY&hl=en&fs=1&" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="425" height="344"></embed></object>
  $output = <<<OUTPUT
        <div id="$div_id"><object type="application/x-shockwave-flash" height="$height" width="$width" data="$url" id="$id">
          <param name="movie" value="$url" />
          <param name="allowScriptAcess" value="sameDomain"/>
          <param name="quality" value="best"/>
          <param name="allowFullScreen" value="$fullscreen_value"/>
          <param name="bgcolor" value="#FFFFFF"/>
          <param name="scale" value="noScale"/>
          <param name="salign" value="TL"/>
          <param name="FlashVars" value="$flashvars" />
          <param name="wmode" value="transparent" />
        </object></div>
OUTPUT;
  return $output;
}
